trigger:
  branches:
    include:
      - refs/tags/*

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: BuildPackPublish
    displayName: build, pack, and publish nuget package
    steps:
      - task: UseDotNet@2
        displayName: set sdk .NET version
        inputs:
          packageType: sdk
          version: "8.0.x"

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: "**/*.csproj"
          includeNuGetOrg: true
          feedsToUse: "select"
          vstsFeed: $(vstsFeed)

      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: build
          arguments: "--configuration Release"
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: dotnet pack
        inputs:
          command: 'pack'
          configuration: 'Release'
          nobuild: true
          outputDir: "$(Build.ArtifactStagingDirectory)/Release"
          packagesToPack: '**/*.csproj'
          versioningScheme: byEnvVar
          versionEnvVar: 'versionNumber'

      - task: DotNetCoreCLI@2
        displayName: dotnet push
        inputs:
          command: 'push'
          nuGetFeedType: 'internal'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/Release/**/*.nupkg'
          publishVstsFeed: $(vstsFeed)