trigger:
  branches:
    include:
      - refs/tags/*

variables:
  - template: variables.yml

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Build
    displayName: Build and Test
    steps:
      - task: UseDotNet@2
        displayName: "Set sdk to .NET 6.0.x"
        inputs:
          packageType: sdk
          version: "6.0.x"

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: "**/*.csproj"
          feedsToUse: "select"
          vstsFeed: $(vstsFeed)

      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: build
          arguments: "--configuration Release"
          projects: "**/*.csproj"
          
  - job: CreateNuGetPackage
    displayName: Create NuGet Package
    dependsOn: Build
    condition: succeeded()
    steps:
    - task: Bash@3
      displayName: "Get Latest Git Tag"
      inputs:
        targetType: "inline"
        script: |
          tag=$(git describe --tags)
          echo $tag
          echo "##vso[task.setvariable variable=GITTAG]$tag"

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: byTag
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: dotnet push
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: $(vstsFeed)