trigger:
  - main

variables:
  - template: devops/variables.yml

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Build
    displayName: Build and Test
    steps:
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: "**/*.csproj"
          feedsToUse: "select"
          nugetConfigPath: "./nuget.config"
          vstsFeed: $(vstsFeed)

      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: build
          arguments: "--configuration Release"
          projects: "**/*.csproj"
          
  - job: CreateNuGetPackage
    displayName: Create NuGet Package
    dependsOn: Build
    condition: succeeded()
    steps:
    - task: Bash@3
      displayName: "Get Latest Git Tag"
      inputs:
        targetType: "inline"
        script: |
          tag=$(git describe --tags)
          echo $tag
          echo "##vso[task.setvariable variable=GITTAG]$tag"

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versionEnvVar: GITTAG
        versioningScheme: byEnvVar

    - task: DotNetCoreCLI@2
      displayName: dotnet push
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '345fc6fa-24df-4e4a-a1ec-41fe6218ebd6/082188ec-3ffc-4d2b-9aa8-680805bf810f'