name: Publish NuGet Packages

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - DepenMock
          - DepenMock.XUnit
          - DepenMock.NUnit
          - DepenMock.MSTest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Check for changes in ${{ matrix.project }}
        id: detect-changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- src/${{ matrix.project }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Restore & Build ${{ matrix.project }}
        if: steps.detect-changes.outputs.changed == 'true'
        run: |
          dotnet restore ${{ matrix.project }}
          dotnet build ${{ matrix.project }} --configuration Release --no-restore

      - name: Test ${{ matrix.project }}
        if: steps.detect-changes.outputs.changed == 'true'
        run: dotnet test ${{ matrix.project }} --configuration Release --no-build

      - name: Pack ${{ matrix.project }}
        if: steps.detect-changes.outputs.changed == 'true'
        run: |
          dotnet pack ${{ matrix.project }} --configuration Release --no-build --output ./nupkgs -p:Version=${VERSION}

      - name: Publish ${{ matrix.project }} to NuGet
        if: steps.detect-changes.outputs.changed == 'true'
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
