name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version and date
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release v${{ env.VERSION }}"
          generate_release_notes: true
          body: |
            ## 🚀 DepenMock v${{ env.VERSION }} – ${{ env.DATE }}

            ### 📦 NuGet Packages Published

            The following packages are available on NuGet.org:
            
            - **DepenMock** - Core testing library
            - **DepenMock.NUnit** - NUnit integration
            - **DepenMock.XUnit** - XUnit integration
            - **DepenMock.MSTest** - MSTest integration

            Install via Package Manager:
            ```
            Install-Package DepenMock -Version ${{ env.VERSION }}
            ```

            Or via .NET CLI:
            ```
            dotnet add package DepenMock --version ${{ env.VERSION }}
            ```

            ### 📝 Release Notes

            _Automatically generated release notes appear below._
